https://github.com/presidenten/rancher-in-kind/blob/master/charts/linkerd-viz/Chart.yaml
https://github.com/linkerd/linkerd2/issues/7510
----------------------
Container

  - containerPort: 4143
    name: linkerd-proxy
    protocol: TCP

  podIP: 10.244.1.184

----------------------
Service

  10.100.255.1 

----------------------

docker@minikube:~$ sudo iptables -t nat
iptables v1.8.7 (nf_tables): no command specified
Try `iptables -h' or 'iptables --help' for more information.
docker@minikube:~$ sudo iptables -t nat -L
Chain PREROUTING (policy ACCEPT)
target         prot opt source               destination         
KUBE-SERVICES  all  --  anywhere             anywhere             /* kubernetes service portals */
DOCKER_OUTPUT  all  --  anywhere             host.minikube.internal 
DOCKER         all  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
KUBE-SERVICES  all  --  anywhere             anywhere             /* kubernetes service portals */
DOCKER_OUTPUT  all  --  anywhere             host.minikube.internal 
DOCKER     all  --  anywhere            !localhost/8          ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
KUBE-POSTROUTING  all  --  anywhere             anywhere             /* kubernetes postrouting rules */
MASQUERADE  all  --  172.17.0.0/16        anywhere            
DOCKER_POSTROUTING  all  --  anywhere             host.minikube.internal 
CNI-2ced9e4b8ed60d7eef0f5927  all  --  10.244.1.176         anywhere             /* name: "bridge" id: "c52617dc61ce482a52411a5be54484302b177a1e9f27de98c0d9f467277fa3f0" */
CNI-2fc190c1c576025c0ca984ac  all  --  10.244.1.177         anywhere             /* name: "bridge" id: "fa3dc483ed2bdb03c87a89929b1fee4f80a2f145e19b09580a144078d4d01bb4" */
CNI-2016ea71a66c4045c3900bdb  all  --  10.244.1.178         anywhere             /* name: "bridge" id: "8570789368cf43b0c75d38390b8923452e1c688cc0a06f12e49d2663640099c2" */
CNI-42e374b41d45d14c85584ba5  all  --  10.244.1.179         anywhere             /* name: "bridge" id: "3f39bb4b2a1e1d25f3000cae7075b7fa72a877e855afb8b6d7b6d06f4ab17451" */
CNI-9f12c07232062d885cb7f7c3  all  --  10.244.1.180         anywhere             /* name: "bridge" id: "e81bac0a9f9c194169bd82b85c63129fc12160eebe233f597ac82d4ed1fc3aa4" */
CNI-f8a46c868252e7199c896428  all  --  10.244.1.183         anywhere             /* name: "bridge" id: "71c8d87c707ddfb25c65d4be723d47a829e1c8d1faf2a66f6b6a827917ee53d7" */

Chain CNI-2016ea71a66c4045c3900bdb (1 references)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             10.244.0.0/16        /* name: "bridge" id: "8570789368cf43b0c75d38390b8923452e1c688cc0a06f12e49d2663640099c2" */
MASQUERADE  all  --  anywhere            !base-address.mcast.net/4  /* name: "bridge" id: "8570789368cf43b0c75d38390b8923452e1c688cc0a06f12e49d2663640099c2" */

Chain CNI-2ced9e4b8ed60d7eef0f5927 (1 references)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             10.244.0.0/16        /* name: "bridge" id: "c52617dc61ce482a52411a5be54484302b177a1e9f27de98c0d9f467277fa3f0" */
MASQUERADE  all  --  anywhere            !base-address.mcast.net/4  /* name: "bridge" id: "c52617dc61ce482a52411a5be54484302b177a1e9f27de98c0d9f467277fa3f0" */

Chain CNI-2fc190c1c576025c0ca984ac (1 references)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             10.244.0.0/16        /* name: "bridge" id: "fa3dc483ed2bdb03c87a89929b1fee4f80a2f145e19b09580a144078d4d01bb4" */
MASQUERADE  all  --  anywhere            !base-address.mcast.net/4  /* name: "bridge" id: "fa3dc483ed2bdb03c87a89929b1fee4f80a2f145e19b09580a144078d4d01bb4" */

Chain CNI-42e374b41d45d14c85584ba5 (1 references)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             10.244.0.0/16        /* name: "bridge" id: "3f39bb4b2a1e1d25f3000cae7075b7fa72a877e855afb8b6d7b6d06f4ab17451" */
MASQUERADE  all  --  anywhere            !base-address.mcast.net/4  /* name: "bridge" id: "3f39bb4b2a1e1d25f3000cae7075b7fa72a877e855afb8b6d7b6d06f4ab17451" */

Chain CNI-9f12c07232062d885cb7f7c3 (1 references)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             10.244.0.0/16        /* name: "bridge" id: "e81bac0a9f9c194169bd82b85c63129fc12160eebe233f597ac82d4ed1fc3aa4" */
MASQUERADE  all  --  anywhere            !base-address.mcast.net/4  /* name: "bridge" id: "e81bac0a9f9c194169bd82b85c63129fc12160eebe233f597ac82d4ed1fc3aa4" */

Chain CNI-f8a46c868252e7199c896428 (1 references)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             10.244.0.0/16        /* name: "bridge" id: "71c8d87c707ddfb25c65d4be723d47a829e1c8d1faf2a66f6b6a827917ee53d7" */
MASQUERADE  all  --  anywhere            !base-address.mcast.net/4  /* name: "bridge" id: "71c8d87c707ddfb25c65d4be723d47a829e1c8d1faf2a66f6b6a827917ee53d7" */

Chain DOCKER (2 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere            

Chain DOCKER_OUTPUT (2 references)
target     prot opt source               destination         
DNAT       tcp  --  anywhere             host.minikube.internal  tcp dpt:domain to:127.0.0.11:36849
DNAT       udp  --  anywhere             host.minikube.internal  udp dpt:domain to:127.0.0.11:57044

Chain DOCKER_POSTROUTING (1 references)
target     prot opt source               destination         
SNAT       tcp  --  localhost            anywhere             to:192.168.49.1:53
SNAT       udp  --  localhost            anywhere             to:192.168.49.1:53

Chain KUBE-EXT-D7TXZ2ONB4DT7BQA (2 references)
target     prot opt source               destination         
KUBE-MARK-MASQ  all  --  anywhere             anywhere             /* masquerade traffic for default/ingress-nginx-controller:http external destinations */
KUBE-SVC-D7TXZ2ONB4DT7BQA  all  --  anywhere             anywhere            

Chain KUBE-EXT-Q7CDIBSFDYNOJNFE (2 references)
target     prot opt source               destination         
KUBE-MARK-MASQ  all  --  anywhere             anywhere             /* masquerade traffic for default/ingress-nginx-controller:https external destinations */
KUBE-SVC-Q7CDIBSFDYNOJNFE  all  --  anywhere             anywhere            

Chain KUBE-KUBELET-CANARY (0 references)
target     prot opt source               destination         

Chain KUBE-MARK-MASQ (28 references)
target     prot opt source               destination         
MARK       all  --  anywhere             anywhere             MARK or 0x4000

Chain KUBE-NODEPORTS (1 references)
target     prot opt source               destination         
KUBE-EXT-Q7CDIBSFDYNOJNFE  tcp  --  anywhere             anywhere             /* default/ingress-nginx-controller:https */
KUBE-EXT-D7TXZ2ONB4DT7BQA  tcp  --  anywhere             anywhere             /* default/ingress-nginx-controller:http */

Chain KUBE-POSTROUTING (1 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere            
MARK       all  --  anywhere             anywhere             MARK xor 0x4000
MASQUERADE  all  --  anywhere             anywhere             /* kubernetes service traffic requiring SNAT */ random-fully

Chain KUBE-PROXY-CANARY (0 references)
target     prot opt source               destination         

Chain KUBE-SEP-2YBCY4GQLRH6S76S (1 references)
target     prot opt source               destination         
KUBE-MARK-MASQ  all  --  10.244.1.177         anywhere             /* default/ingress-nginx-controller-admission:https-webhook */
DNAT       tcp  --  anywhere             anywhere             /* default/ingress-nginx-controller-admission:https-webhook */ tcp to:10.244.1.177:8443

Chain KUBE-SEP-5DGYGN5RPTNHCJOA (1 references)
target     prot opt source               destination         
KUBE-MARK-MASQ  all  --  10.244.1.183         anywhere             /* linkerd/linkerd-sp-validator:sp-validator */
DNAT       tcp  --  anywhere             anywhere             /* linkerd/linkerd-sp-validator:sp-validator */ tcp to:10.244.1.183:8443

Chain KUBE-SEP-6B5LIWIMLG5FUTKX (1 references)
target     prot opt source               destination         
KUBE-MARK-MASQ  all  --  10.244.1.179         anywhere             /* linkerd/linkerd-proxy-injector:proxy-injector */
DNAT       tcp  --  anywhere             anywhere             /* linkerd/linkerd-proxy-injector:proxy-injector */ tcp to:10.244.1.179:8443

Chain KUBE-SEP-EAJOOWGGK7P2AWSM (1 references)
target     prot opt source               destination         
KUBE-MARK-MASQ  all  --  10.244.1.176         anywhere             /* kube-system/kube-dns:metrics */
DNAT       tcp  --  anywhere             anywhere             /* kube-system/kube-dns:metrics */ tcp to:10.244.1.176:9153

Chain KUBE-SEP-JTHHROA2MIOXP6DG (1 references)
target     prot opt source               destination         
KUBE-MARK-MASQ  all  --  10.244.1.176         anywhere             /* kube-system/kube-dns:dns */
DNAT       udp  --  anywhere             anywhere             /* kube-system/kube-dns:dns */ udp to:10.244.1.176:53

Chain KUBE-SEP-KXEZS7PDF2JRUCBY (1 references)
target     prot opt source               destination         
KUBE-MARK-MASQ  all  --  10.244.1.180         anywhere             /* vastaya/application-vastaya-svc:http */
DNAT       tcp  --  anywhere             anywhere             /* vastaya/application-vastaya-svc:http */ tcp to:10.244.1.180:80

Chain KUBE-SEP-MGPETHGPZZOOUJOX (1 references)
target     prot opt source               destination         
KUBE-MARK-MASQ  all  --  10.244.1.176         anywhere             /* kube-system/kube-dns:dns-tcp */
DNAT       tcp  --  anywhere             anywhere             /* kube-system/kube-dns:dns-tcp */ tcp to:10.244.1.176:53

Chain KUBE-SEP-PDND4PGGCEUUOK3N (1 references)
target     prot opt source               destination         
KUBE-MARK-MASQ  all  --  10.244.1.177         anywhere             /* default/ingress-nginx-controller:http */
DNAT       tcp  --  anywhere             anywhere             /* default/ingress-nginx-controller:http */ tcp to:10.244.1.177:80

Chain KUBE-SEP-VPILYQBSPPXYB66K (1 references)
target     prot opt source               destination         
KUBE-MARK-MASQ  all  --  minikube             anywhere             /* default/kubernetes:https */
DNAT       tcp  --  anywhere             anywhere             /* default/kubernetes:https */ tcp to:192.168.49.2:8443

Chain KUBE-SEP-W2634P7EQHA4A4IA (1 references)
target     prot opt source               destination         
KUBE-MARK-MASQ  all  --  10.244.1.178         anywhere             /* linkerd/linkerd-identity:grpc */
DNAT       tcp  --  anywhere             anywhere             /* linkerd/linkerd-identity:grpc */ tcp to:10.244.1.178:8080

Chain KUBE-SEP-WTG4TRXGD5CRHPEC (1 references)
target     prot opt source               destination         
KUBE-MARK-MASQ  all  --  10.244.1.177         anywhere             /* default/ingress-nginx-controller:https */
DNAT       tcp  --  anywhere             anywhere             /* default/ingress-nginx-controller:https */ tcp to:10.244.1.177:443

Chain KUBE-SEP-ZQJROIY4NP74X27T (1 references)
target     prot opt source               destination         
KUBE-MARK-MASQ  all  --  10.244.1.183         anywhere             /* linkerd/linkerd-dst:grpc */
DNAT       tcp  --  anywhere             anywhere             /* linkerd/linkerd-dst:grpc */ tcp to:10.244.1.183:8086

Chain KUBE-SEP-ZTDDIXCB2ZQKDKHN (1 references)
target     prot opt source               destination         
KUBE-MARK-MASQ  all  --  10.244.1.183         anywhere             /* linkerd/linkerd-policy-validator:policy-https */
DNAT       tcp  --  anywhere             anywhere             /* linkerd/linkerd-policy-validator:policy-https */ tcp to:10.244.1.183:9443

Chain KUBE-SERVICES (2 references)
target                     prot opt source               destination         
KUBE-SVC-Z54HJDVTKAHYPJRW  tcp  --  anywhere             10.97.198.154        /* linkerd/linkerd-dst:grpc cluster IP */
KUBE-SVC-Q7CDIBSFDYNOJNFE  tcp  --  anywhere             vastaya.tech         /* default/ingress-nginx-controller:https cluster IP */
KUBE-EXT-Q7CDIBSFDYNOJNFE  tcp  --  anywhere             vastaya.tech         /* default/ingress-nginx-controller:https loadbalancer IP */
KUBE-SVC-U2TN5MI3KW4FHINL  tcp  --  anywhere             10.104.253.3         /* linkerd/linkerd-identity:grpc cluster IP */
KUBE-SVC-4XXDOENHIN7KG3DR  tcp  --  anywhere             10.98.143.249        /* linkerd/linkerd-proxy-injector:proxy-injector cluster IP */
KUBE-SVC-XUD33RTORZBRAEIL  tcp  --  anywhere             10.96.27.17          /* default/ingress-nginx-controller-admission:https-webhook cluster IP */
KUBE-SVC-JD5MR3NA4I4DYORP  tcp  --  anywhere             10.96.0.10           /* kube-system/kube-dns:metrics cluster IP */
KUBE-SVC-QC6GMSWWJ7LEIVL3  tcp  --  anywhere             10.105.82.184        /* linkerd/linkerd-sp-validator:sp-validator cluster IP */
KUBE-SVC-D7TXZ2ONB4DT7BQA  tcp  --  anywhere             vastaya.tech         /* default/ingress-nginx-controller:http cluster IP */
KUBE-EXT-D7TXZ2ONB4DT7BQA  tcp  --  anywhere             vastaya.tech         /* default/ingress-nginx-controller:http loadbalancer IP */
KUBE-SVC-TCOU7JCQXEZGVUNU  udp  --  anywhere             10.96.0.10           /* kube-system/kube-dns:dns cluster IP */
KUBE-SVC-ERIFXISQEP7F7OF4  tcp  --  anywhere             10.96.0.10           /* kube-system/kube-dns:dns-tcp cluster IP */
KUBE-SVC-5ER24GSKSR367UIA  tcp  --  anywhere             10.100.255.1         /* vastaya/application-vastaya-svc:http cluster IP */
KUBE-SVC-NPX46M4PTMTKRN6Y  tcp  --  anywhere             10.96.0.1            /* default/kubernetes:https cluster IP */
KUBE-SVC-JKJ2UJ6XMMJIJGSF  tcp  --  anywhere             10.102.211.91        /* linkerd/linkerd-policy-validator:policy-https cluster IP */
KUBE-NODEPORTS             all  --  anywhere             anywhere             /* kubernetes service nodeports; NOTE: this must be the last rule in this chain */ ADDRTYPE match dst-type LOCAL

Chain KUBE-SVC-4XXDOENHIN7KG3DR (1 references)
target     prot opt source               destination         
KUBE-MARK-MASQ  tcp  -- !10.244.0.0/16        10.98.143.249        /* linkerd/linkerd-proxy-injector:proxy-injector cluster IP */
KUBE-SEP-6B5LIWIMLG5FUTKX  all  --  anywhere             anywhere             /* linkerd/linkerd-proxy-injector:proxy-injector -> 10.244.1.179:8443 */

Chain KUBE-SVC-5ER24GSKSR367UIA (1 references)
target                     prot opt source               destination         
KUBE-MARK-MASQ             tcp  -- !10.244.0.0/16        10.100.255.1         /* vastaya/application-vastaya-svc:http cluster IP */
KUBE-SEP-KXEZS7PDF2JRUCBY  all  --  anywhere             anywhere             /* vastaya/application-vastaya-svc:http -> 10.244.1.180:80 */

Chain KUBE-SVC-D7TXZ2ONB4DT7BQA (2 references)
target     prot opt source               destination         
KUBE-MARK-MASQ  tcp  -- !10.244.0.0/16        vastaya.tech         /* default/ingress-nginx-controller:http cluster IP */
KUBE-SEP-PDND4PGGCEUUOK3N  all  --  anywhere             anywhere             /* default/ingress-nginx-controller:http -> 10.244.1.177:80 */

Chain KUBE-SVC-ERIFXISQEP7F7OF4 (1 references)
target     prot opt source               destination         
KUBE-MARK-MASQ  tcp  -- !10.244.0.0/16        10.96.0.10           /* kube-system/kube-dns:dns-tcp cluster IP */
KUBE-SEP-MGPETHGPZZOOUJOX  all  --  anywhere             anywhere             /* kube-system/kube-dns:dns-tcp -> 10.244.1.176:53 */

Chain KUBE-SVC-JD5MR3NA4I4DYORP (1 references)
target     prot opt source               destination         
KUBE-MARK-MASQ  tcp  -- !10.244.0.0/16        10.96.0.10           /* kube-system/kube-dns:metrics cluster IP */
KUBE-SEP-EAJOOWGGK7P2AWSM  all  --  anywhere             anywhere             /* kube-system/kube-dns:metrics -> 10.244.1.176:9153 */

Chain KUBE-SVC-JKJ2UJ6XMMJIJGSF (1 references)
target     prot opt source               destination         
KUBE-MARK-MASQ  tcp  -- !10.244.0.0/16        10.102.211.91        /* linkerd/linkerd-policy-validator:policy-https cluster IP */
KUBE-SEP-ZTDDIXCB2ZQKDKHN  all  --  anywhere             anywhere             /* linkerd/linkerd-policy-validator:policy-https -> 10.244.1.183:9443 */

Chain KUBE-SVC-NPX46M4PTMTKRN6Y (1 references)
target     prot opt source               destination         
KUBE-MARK-MASQ  tcp  -- !10.244.0.0/16        10.96.0.1            /* default/kubernetes:https cluster IP */
KUBE-SEP-VPILYQBSPPXYB66K  all  --  anywhere             anywhere             /* default/kubernetes:https -> 192.168.49.2:8443 */

Chain KUBE-SVC-Q7CDIBSFDYNOJNFE (2 references)
target     prot opt source               destination         
KUBE-MARK-MASQ  tcp  -- !10.244.0.0/16        vastaya.tech         /* default/ingress-nginx-controller:https cluster IP */
KUBE-SEP-WTG4TRXGD5CRHPEC  all  --  anywhere             anywhere             /* default/ingress-nginx-controller:https -> 10.244.1.177:443 */

Chain KUBE-SVC-QC6GMSWWJ7LEIVL3 (1 references)
target     prot opt source               destination         
KUBE-MARK-MASQ  tcp  -- !10.244.0.0/16        10.105.82.184        /* linkerd/linkerd-sp-validator:sp-validator cluster IP */
KUBE-SEP-5DGYGN5RPTNHCJOA  all  --  anywhere             anywhere             /* linkerd/linkerd-sp-validator:sp-validator -> 10.244.1.183:8443 */

Chain KUBE-SVC-TCOU7JCQXEZGVUNU (1 references)
target     prot opt source               destination         
KUBE-MARK-MASQ  udp  -- !10.244.0.0/16        10.96.0.10           /* kube-system/kube-dns:dns cluster IP */
KUBE-SEP-JTHHROA2MIOXP6DG  all  --  anywhere             anywhere             /* kube-system/kube-dns:dns -> 10.244.1.176:53 */

Chain KUBE-SVC-U2TN5MI3KW4FHINL (1 references)
target     prot opt source               destination         
KUBE-MARK-MASQ  tcp  -- !10.244.0.0/16        10.104.253.3         /* linkerd/linkerd-identity:grpc cluster IP */
KUBE-SEP-W2634P7EQHA4A4IA  all  --  anywhere             anywhere             /* linkerd/linkerd-identity:grpc -> 10.244.1.178:8080 */

Chain KUBE-SVC-XUD33RTORZBRAEIL (1 references)
target     prot opt source               destination         
KUBE-MARK-MASQ  tcp  -- !10.244.0.0/16        10.96.27.17          /* default/ingress-nginx-controller-admission:https-webhook cluster IP */
KUBE-SEP-2YBCY4GQLRH6S76S  all  --  anywhere             anywhere             /* default/ingress-nginx-controller-admission:https-webhook -> 10.244.1.177:8443 */

Chain KUBE-SVC-Z54HJDVTKAHYPJRW (1 references)
target     prot opt source               destination         
KUBE-MARK-MASQ  tcp  -- !10.244.0.0/16        10.97.198.154        /* linkerd/linkerd-dst:grpc cluster IP */
KUBE-SEP-ZQJROIY4NP74X27T  all  --  anywhere             anywhere             /* linkerd/linkerd-dst:grpc -> 10.244.1.183:8086 */
