# apiVersion: gateway.networking.k8s.io/v1beta1
apiVersion: policy.linkerd.io/v1beta2
kind: HTTPRoute
metadata:
  name: project-vastaya-traffic-split
  namespace: vastaya
spec:
  hostnames:
  - projects.vastaya.tech
  - projects-vastaya-svc.vastaya.svc.cluster.local
  # parentRefs:
  #   - name: projects-vastaya-svc
  #     kind: Service
  #     namespace: vastaya
  #     port: 80
  rules:
  - backendRefs:
    # - name: projects-vastaya-svc
    #   port: 80
    #   weight: 50  # Adjust the weight as needed
    - name: projects-canary-vastaya-svc
      port: 80
      # weight: 50  # Adjust the weight as needed
      